# Generated by Django 5.0.1 on 2024-01-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipeImage',
            field=models.FileField(null=True, upload_to='recipe'),
        ),
    ]
