# Generated by Django 5.0.1 on 2024-01-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0003_recipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipeViewCount',
            field=models.IntegerField(default=1),
        ),
    ]
